[package]
name = "rawproc"
version = "0.1.0"
authors = ["Brad Alfirevic <brad@genbyte.dev>"]
edition = "2018"

[dependencies]
num-traits = "0.2.14"
libraw-rs = { path = "../libraw-rs/libraw" }
rand = "0.7"