[package]
name = "easyraw"
version = "0.1.0"
authors = ["Brad Alfirevic <brad@genbyte.dev>"]
edition = "2018"

[dependencies]
getopts = "0.2.21"
libraw-rs = { path = "../libraw-rs/libraw" }
png = "0.16"
rand = "0.7"